### ISSUE TITLE
tied_sequenceのdataメンバ関数について

### ISSUE THREAD

**Issue by sukeya** [Flast/flat_map#24]
`tied_sequence`に`std::deque`を使った場合、`std::deque`には`data`メンバ関数がないのでコンパイルエラーが出ます。

**Comment by Flast** [comment]
ドキュメントを参照してください
https://github.com/Flast/flat_map/blob/master/docs/tied_sequence.md#data

**Comment by sukeya** [comment]
ドキュメント見てませんでした。すみません。
