### ISSUE TITLE
なぜtied_sequenceのreserve、capacity、shrink_to_fitメンバ関数が無効?

### ISSUE THREAD

**Issue by sukeya** [Flast/flat_map#25]
使わない関数が例えコンパイルエラーになったとしても無視されるのであれば、問題ない気がしますが...

**Comment by Flast** [comment]
ユースケースも多くなく、優先度も低いので実装してないだけです

**Comment by sukeya** [comment]
そうなんですね。
ユースケースについてですが、自分は大量の値を扱うのでメモリ確保の回数を少なくするために`reserve`をかなり使っています。
しかし、#23 次第では使わなくなるかもしれません。

**Comment by sukeya** [comment]
大体実装できているように見えますが、私で良ければお手伝いしましょうか？
